<?php
	global $wd_google_fonts,$wd_widget_area;
	$wd_google_fonts = array(
		"none" => "Select a font"
		,"ABeeZee" => "ABeeZee"
		,"Abel" => "Abel"
		,"Abril Fatface" => "Abril Fatface"
		,"Aclonica" => "Aclonica"
		,"Acme" => "Acme"
		,"Actor" => "Actor"
		,"Adamina" => "Adamina"
		,"Open Sans" => "Open Sans"
		,"Aguafina Script" => "Aguafina Script"
		,"Akronim" => "Akronim"
		,"Aladin" => "Aladin"
		,"Aldrich" => "Aldrich"
		,"Alef" => "Alef"
		,"Alegreya" => "Alegreya"
		,"Alegreya SC" => "Alegreya SC"
		,"Alex Brush" => "Alex Brush"
		,"Alfa Slab One" => "Alfa Slab One"
		,"Alice" => "Alice"
		,"Alike" => "Alike"
		,"Alike Angular" => "Alike Angular"
		,"Allan" => "Allan"
		,"Allerta" => "Allerta"
		,"Allerta Stencil" => "Allerta Stencil"
		,"Allura" => "Allura"
		,"Almendra" => "Almendra"
		,"Almendra Display" => "Almendra Display"
		,"Almendra SC" => "Almendra SC"
		,"Amarante" => "Amarante"
		,"Amaranth" => "Amaranth"
		,"Amatic SC" => "Amatic SC"
		,"Amethysta" => "Amethysta"
		,"Anaheim" => "Anaheim"
		,"Andada" => "Andada"
		,"Andika" => "Andika"
		,"Angkor" => "Angkor"
		,"Annie Use Your Telescope" => "Annie Use Your Telescope"
		,"Anonymous Pro" => "Anonymous Pro"
		,"Antic" => "Antic"
		,"Antic Didone" => "Antic Didone"
		,"Antic Slab" => "Antic Slab"
		,"Anton" => "Anton"
		,"Arapey" => "Arapey"
		,"Arbutus" => "Arbutus"
		,"Arbutus Slab" => "Arbutus Slab"
		,"Architects Daughter" => "Architects Daughter"
		,"Archivo Black" => "Archivo Black"
		,"Archivo Narrow" => "Archivo Narrow"
		,"Arimo" => "Arimo"
		,"Arizonia" => "Arizonia"
		,"Armata" => "Armata"
		,"Artifika" => "Artifika"
		,"Arvo" => "Arvo"
		,"Asap" => "Asap"
		,"Asset" => "Asset"
		,"Astloch" => "Astloch"
		,"Asul" => "Asul"
		,"Atomic Age" => "Atomic Age"
		,"Aubrey" => "Aubrey"
		,"Audiowide" => "Audiowide"
		,"Autour One" => "Autour One"
		,"Average" => "Average"
		,"Average Sans" => "Average Sans"
		,"Averia Gruesa Libre" => "Averia Gruesa Libre"
		,"Averia Libre" => "Averia Libre"
		,"Averia Sans Libre" => "Averia Sans Libre"
		,"Averia Serif Libre" => "Averia Serif Libre"
		,"Bad Script" => "Bad Script"
		,"Balthazar" => "Balthazar"
		,"Bangers" => "Bangers"
		,"Basic" => "Basic"
		,"Battambang" => "Battambang"
		,"Baumans" => "Baumans"
		,"Bayon" => "Bayon"
		,"Belgrano" => "Belgrano"
		,"Belleza" => "Belleza"
		,"BenchNine" => "BenchNine"
		,"Bentham" => "Bentham"
		,"Berkshire Swash" => "Berkshire Swash"
		,"Bevan" => "Bevan"
		,"Bigelow Rules" => "Bigelow Rules"
		,"Bigshot One" => "Bigshot One"
		,"Bilbo" => "Bilbo"
		,"Bilbo Swash Caps" => "Bilbo Swash Caps"
		,"Bitter" => "Bitter"
		,"Black Ops One" => "Black Ops One"
		,"Bokor" => "Bokor"
		,"Bonbon" => "Bonbon"
		,"Boogaloo" => "Boogaloo"
		,"Bowlby One" => "Bowlby One"
		,"Bowlby One SC" => "Bowlby One SC"
		,"Brawler" => "Brawler"
		,"Bree Serif" => "Bree Serif"
		,"Bubblegum Sans" => "Bubblegum Sans"
		,"Bubbler One" => "Bubbler One"
		,"Buda" => "Buda"
		,"Buenard" => "Buenard"
		,"Butcherman" => "Butcherman"
		,"Butterfly Kids" => "Butterfly Kids"
		,"Cabin" => "Cabin"
		,"Cabin Condensed" => "Cabin Condensed"
		,"Cabin Sketch" => "Cabin Sketch"
		,"Caesar Dressing" => "Caesar Dressing"
		,"Cagliostro" => "Cagliostro"
		,"Calligraffitti" => "Calligraffitti"
		,"Cambo" => "Cambo"
		,"Candal" => "Candal"
		,"Cantarell" => "Cantarell"
		,"Cantata One" => "Cantata One"
		,"Cantora One" => "Cantora One"
		,"Capriola" => "Capriola"
		,"Cardo" => "Cardo"
		,"Carme" => "Carme"
		,"Carrois Gothic" => "Carrois Gothic"
		,"Carrois Gothic SC" => "Carrois Gothic SC"
		,"Carter One" => "Carter One"
		,"Caudex" => "Caudex"
		,"Cedarville Cursive" => "Cedarville Cursive"
		,"Ceviche One" => "Ceviche One"
		,"Changa One" => "Changa One"
		,"Chango" => "Chango"
		,"Chau Philomene One" => "Chau Philomene One"
		,"Chela One" => "Chela One"
		,"Chelsea Market" => "Chelsea Market"
		,"Chenla" => "Chenla"
		,"Cherry Cream Soda" => "Cherry Cream Soda"
		,"Cherry Swash" => "Cherry Swash"
		,"Chewy" => "Chewy"
		,"Chicle" => "Chicle"
		,"Chivo" => "Chivo"
		,"Cinzel" => "Cinzel"
		,"Cinzel Decorative" => "Cinzel Decorative"
		,"Clicker Script" => "Clicker Script"
		,"Coda" => "Coda"
		,"Coda Caption" => "Coda Caption"
		,"Codystar" => "Codystar"
		,"Combo" => "Combo"
		,"Comfortaa" => "Comfortaa"
		,"Coming Soon" => "Coming Soon"
		,"Concert One" => "Concert One"
		,"Condiment" => "Condiment"
		,"Content" => "Content"
		,"Contrail One" => "Contrail One"
		,"Convergence" => "Convergence"
		,"Cookie" => "Cookie"
		,"Copse" => "Copse"
		,"Corben" => "Corben"
		,"Courgette" => "Courgette"
		,"Cousine" => "Cousine"
		,"Coustard" => "Coustard"
		,"Covered By Your Grace" => "Covered By Your Grace"
		,"Crafty Girls" => "Crafty Girls"
		,"Creepster" => "Creepster"
		,"Crete Round" => "Crete Round"
		,"Crimson Text" => "Crimson Text"
		,"Croissant One" => "Croissant One"
		,"Crushed" => "Crushed"
		,"Cuprum" => "Cuprum"
		,"Cutive" => "Cutive"
		,"Cutive Mono" => "Cutive Mono"
		,"Damion" => "Damion"
		,"Dancing Script" => "Dancing Script"
		,"Dangrek" => "Dangrek"
		,"Dawning of a New Day" => "Dawning of a New Day"
		,"Days One" => "Days One"
		,"Delius" => "Delius"
		,"Delius Swash Caps" => "Delius Swash Caps"
		,"Delius Unicase" => "Delius Unicase"
		,"Della Respira" => "Della Respira"
		,"Denk One" => "Denk One"
		,"Devonshire" => "Devonshire"
		,"Didact Gothic" => "Didact Gothic"
		,"Diplomata" => "Diplomata"
		,"Diplomata SC" => "Diplomata SC"
		,"Domine" => "Domine"
		,"Donegal One" => "Donegal One"
		,"Doppio One" => "Doppio One"
		,"Dorsa" => "Dorsa"
		,"Dosis" => "Dosis"
		,"Dr Sugiyama" => "Dr Sugiyama"
		,"Droid Sans" => "Droid Sans"
		,"Droid Sans Mono" => "Droid Sans Mono"
		,"Droid Serif" => "Droid Serif"
		,"Duru Sans" => "Duru Sans"
		,"Dynalight" => "Dynalight"
		,"EB Garamond" => "EB Garamond"
		,"Eagle Lake" => "Eagle Lake"
		,"Eater" => "Eater"
		,"Economica" => "Economica"
		,"Electrolize" => "Electrolize"
		,"Elsie" => "Elsie"
		,"Elsie Swash Caps" => "Elsie Swash Caps"
		,"Emblema One" => "Emblema One"
		,"Emilys Candy" => "Emilys Candy"
		,"Engagement" => "Engagement"
		,"Englebert" => "Englebert"
		,"Enriqueta" => "Enriqueta"
		,"Erica One" => "Erica One"
		,"Esteban" => "Esteban"
		,"Euphoria Script" => "Euphoria Script"
		,"Ewert" => "Ewert"
		,"Exo" => "Exo"
		,"Expletus Sans" => "Expletus Sans"
		,"Fanwood Text" => "Fanwood Text"
		,"Fascinate" => "Fascinate"
		,"Fascinate Inline" => "Fascinate Inline"
		,"Faster One" => "Faster One"
		,"Fasthand" => "Fasthand"
		,"Fauna One" => "Fauna One"
		,"Federant" => "Federant"
		,"Federo" => "Federo"
		,"Felipa" => "Felipa"
		,"Fenix" => "Fenix"
		,"Finger Paint" => "Finger Paint"
		,"Fjalla One" => "Fjalla One"
		,"Fjord One" => "Fjord One"
		,"Flamenco" => "Flamenco"
		,"Flavors" => "Flavors"
		,"Fondamento" => "Fondamento"
		,"Fontdiner Swanky" => "Fontdiner Swanky"
		,"Forum" => "Forum"
		,"Francois One" => "Francois One"
		,"Freckle Face" => "Freckle Face"
		,"Fredericka the Great" => "Fredericka the Great"
		,"Fredoka One" => "Fredoka One"
		,"Freehand" => "Freehand"
		,"Fresca" => "Fresca"
		,"Frijole" => "Frijole"
		,"Fruktur" => "Fruktur"
		,"Fugaz One" => "Fugaz One"
		,"GFS Didot" => "GFS Didot"
		,"GFS Neohellenic" => "GFS Neohellenic"
		,"Gabriela" => "Gabriela"
		,"Gafata" => "Gafata"
		,"Galdeano" => "Galdeano"
		,"Galindo" => "Galindo"
		,"Gentium Basic" => "Gentium Basic"
		,"Gentium Book Basic" => "Gentium Book Basic"
		,"Geo" => "Geo"
		,"Geostar" => "Geostar"
		,"Geostar Fill" => "Geostar Fill"
		,"Germania One" => "Germania One"
		,"Gilda Display" => "Gilda Display"
		,"Give You Glory" => "Give You Glory"
		,"Glass Antiqua" => "Glass Antiqua"
		,"Glegoo" => "Glegoo"
		,"Gloria Hallelujah" => "Gloria Hallelujah"
		,"Goblin One" => "Goblin One"
		,"Gochi Hand" => "Gochi Hand"
		,"Gorditas" => "Gorditas"
		,"Goudy Bookletter 1911" => "Goudy Bookletter 1911"
		,"Graduate" => "Graduate"
		,"Grand Hotel" => "Grand Hotel"
		,"Gravitas One" => "Gravitas One"
		,"Great Vibes" => "Great Vibes"
		,"Griffy" => "Griffy"
		,"Gruppo" => "Gruppo"
		,"Gudea" => "Gudea"
		,"Habibi" => "Habibi"
		,"Hammersmith One" => "Hammersmith One"
		,"Hanalei" => "Hanalei"
		,"Hanalei Fill" => "Hanalei Fill"
		,"Handlee" => "Handlee"
		,"Hanuman" => "Hanuman"
		,"Happy Monkey" => "Happy Monkey"
		,"Headland One" => "Headland One"
		,"Henny Penny" => "Henny Penny"
		,"Herr Von Muellerhoff" => "Herr Von Muellerhoff"
		,"Holtwood One SC" => "Holtwood One SC"
		,"Homemade Apple" => "Homemade Apple"
		,"Homenaje" => "Homenaje"
		,"IM Fell DW Pica" => "IM Fell DW Pica"
		,"IM Fell DW Pica SC" => "IM Fell DW Pica SC"
		,"IM Fell Double Pica" => "IM Fell Double Pica"
		,"IM Fell Double Pica SC" => "IM Fell Double Pica SC"
		,"IM Fell English" => "IM Fell English"
		,"IM Fell English SC" => "IM Fell English SC"
		,"IM Fell French Canon" => "IM Fell French Canon"
		,"IM Fell French Canon SC" => "IM Fell French Canon SC"
		,"IM Fell Great Primer" => "IM Fell Great Primer"
		,"IM Fell Great Primer SC" => "IM Fell Great Primer SC"
		,"Iceberg" => "Iceberg"
		,"Iceland" => "Iceland"
		,"Imprima" => "Imprima"
		,"Inconsolata" => "Inconsolata"
		,"Inder" => "Inder"
		,"Indie Flower" => "Indie Flower"
		,"Inika" => "Inika"
		,"Irish Grover" => "Irish Grover"
		,"Istok Web" => "Istok Web"
		,"Italiana" => "Italiana"
		,"Italianno" => "Italianno"
		,"Jacques Francois" => "Jacques Francois"
		,"Jacques Francois Shadow" => "Jacques Francois Shadow"
		,"Jim Nightshade" => "Jim Nightshade"
		,"Jockey One" => "Jockey One"
		,"Jolly Lodger" => "Jolly Lodger"
		,"Josefin Sans" => "Josefin Sans"
		,"Josefin Slab" => "Josefin Slab"
		,"Joti One" => "Joti One"
		,"Judson" => "Judson"
		,"Julee" => "Julee"
		,"Julius Sans One" => "Julius Sans One"
		,"Junge" => "Junge"
		,"Jura" => "Jura"
		,"Just Another Hand" => "Just Another Hand"
		,"Just Me Again Down Here" => "Just Me Again Down Here"
		,"Kameron" => "Kameron"
		,"Karla" => "Karla"
		,"Kaushan Script" => "Kaushan Script"
		,"Kavoon" => "Kavoon"
		,"Keania One" => "Keania One"
		,"Kelly Slab" => "Kelly Slab"
		,"Kenia" => "Kenia"
		,"Khmer" => "Khmer"
		,"Kite One" => "Kite One"
		,"Knewave" => "Knewave"
		,"Kotta One" => "Kotta One"
		,"Koulen" => "Koulen"
		,"Kranky" => "Kranky"
		,"Kreon" => "Kreon"
		,"Kristi" => "Kristi"
		,"Krona One" => "Krona One"
		,"La Belle Aurore" => "La Belle Aurore"
		,"Lancelot" => "Lancelot"
		,"Lato" => "Lato"
		,"League Script" => "League Script"
		,"Leckerli One" => "Leckerli One"
		,"Ledger" => "Ledger"
		,"Lekton" => "Lekton"
		,"Lemon" => "Lemon"
		,"Libre Baskerville" => "Libre Baskerville"
		,"Life Savers" => "Life Savers"
		,"Lilita One" => "Lilita One"
		,"Lily Script One" => "Lily Script One"
		,"Limelight" => "Limelight"
		,"Linden Hill" => "Linden Hill"
		,"Lobster" => "Lobster"
		,"Lobster Two" => "Lobster Two"
		,"Londrina Outline" => "Londrina Outline"
		,"Londrina Shadow" => "Londrina Shadow"
		,"Londrina Sketch" => "Londrina Sketch"
		,"Londrina Solid" => "Londrina Solid"
		,"Lora" => "Lora"
		,"Love Ya Like A Sister" => "Love Ya Like A Sister"
		,"Loved by the King" => "Loved by the King"
		,"Lovers Quarrel" => "Lovers Quarrel"
		,"Luckiest Guy" => "Luckiest Guy"
		,"Lusitana" => "Lusitana"
		,"Lustria" => "Lustria"
		,"Macondo" => "Macondo"
		,"Macondo Swash Caps" => "Macondo Swash Caps"
		,"Magra" => "Magra"
		,"Maiden Orange" => "Maiden Orange"
		,"Mako" => "Mako"
		,"Marcellus" => "Marcellus"
		,"Marcellus SC" => "Marcellus SC"
		,"Marck Script" => "Marck Script"
		,"Margarine" => "Margarine"
		,"Marko One" => "Marko One"
		,"Marmelad" => "Marmelad"
		,"Marvel" => "Marvel"
		,"Mate" => "Mate"
		,"Mate SC" => "Mate SC"
		,"Maven Pro" => "Maven Pro"
		,"McLaren" => "McLaren"
		,"Meddon" => "Meddon"
		,"MedievalSharp" => "MedievalSharp"
		,"Medula One" => "Medula One"
		,"Megrim" => "Megrim"
		,"Meie Script" => "Meie Script"
		,"Merienda" => "Merienda"
		,"Merienda One" => "Merienda One"
		,"Merriweather" => "Merriweather"
		,"Merriweather Sans" => "Merriweather Sans"
		,"Metal" => "Metal"
		,"Metal Mania" => "Metal Mania"
		,"Metamorphous" => "Metamorphous"
		,"Metrophobic" => "Metrophobic"
		,"Michroma" => "Michroma"
		,"Milonga" => "Milonga"
		,"Miltonian" => "Miltonian"
		,"Miltonian Tattoo" => "Miltonian Tattoo"
		,"Miniver" => "Miniver"
		,"Miss Fajardose" => "Miss Fajardose"
		,"Modern Antiqua" => "Modern Antiqua"
		,"Molengo" => "Molengo"
		,"Molle" => "Molle"
		,"Monda" => "Monda"
		,"Monofett" => "Monofett"
		,"Monoton" => "Monoton"
		,"Monsieur La Doulaise" => "Monsieur La Doulaise"
		,"Montaga" => "Montaga"
		,"Montez" => "Montez"
		,"Montserrat" => "Montserrat"
		,"Montserrat Alternates" => "Montserrat Alternates"
		,"Montserrat Subrayada" => "Montserrat Subrayada"
		,"Moul" => "Moul"
		,"Moulpali" => "Moulpali"
		,"Mountains of Christmas" => "Mountains of Christmas"
		,"Mouse Memoirs" => "Mouse Memoirs"
		,"Mr Bedfort" => "Mr Bedfort"
		,"Mr Dafoe" => "Mr Dafoe"
		,"Mr De Haviland" => "Mr De Haviland"
		,"Mrs Saint Delafield" => "Mrs Saint Delafield"
		,"Mrs Sheppards" => "Mrs Sheppards"
		,"Muli" => "Muli"
		,"Mystery Quest" => "Mystery Quest"
		,"Neucha" => "Neucha"
		,"Neuton" => "Neuton"
		,"New Rocker" => "New Rocker"
		,"News Cycle" => "News Cycle"
		,"Niconne" => "Niconne"
		,"Nixie One" => "Nixie One"
		,"Nobile" => "Nobile"
		,"Nokora" => "Nokora"
		,"Norican" => "Norican"
		,"Nosifer" => "Nosifer"
		,"Nothing You Could Do" => "Nothing You Could Do"
		,"Noticia Text" => "Noticia Text"
		,"Noto Sans" => "Noto Sans"
		,"Noto Serif" => "Noto Serif"
		,"Nova Cut" => "Nova Cut"
		,"Nova Flat" => "Nova Flat"
		,"Nova Mono" => "Nova Mono"
		,"Nova Oval" => "Nova Oval"
		,"Nova Round" => "Nova Round"
		,"Nova Script" => "Nova Script"
		,"Nova Slim" => "Nova Slim"
		,"Nova Square" => "Nova Square"
		,"Numans" => "Numans"
		,"Nunito" => "Nunito"
		,"Odor Mean Chey" => "Odor Mean Chey"
		,"Offside" => "Offside"
		,"Old Standard TT" => "Old Standard TT"
		,"Oldenburg" => "Oldenburg"
		,"Oleo Script" => "Oleo Script"
		,"Oleo Script Swash Caps" => "Oleo Script Swash Caps"
		,"Open Sans" => "Open Sans"
		,"Open Sans Condensed" => "Open Sans Condensed"
		,"Oranienbaum" => "Oranienbaum"
		,"Orbitron" => "Orbitron"
		,"Oregano" => "Oregano"
		,"Orienta" => "Orienta"
		,"Original Surfer" => "Original Surfer"
		,"Oswald" => "Oswald"
		,"Over the Rainbow" => "Over the Rainbow"
		,"Overlock" => "Overlock"
		,"Overlock SC" => "Overlock SC"
		,"Ovo" => "Ovo"
		,"Oxygen" => "Oxygen"
		,"Oxygen Mono" => "Oxygen Mono"
		,"PT Mono" => "PT Mono"
		,"PT Sans" => "PT Sans"
		,"PT Sans Caption" => "PT Sans Caption"
		,"PT Sans Narrow" => "PT Sans Narrow"
		,"PT Serif" => "PT Serif"
		,"PT Serif Caption" => "PT Serif Caption"
		,"Pacifico" => "Pacifico"
		,"Paprika" => "Paprika"
		,"Parisienne" => "Parisienne"
		,"Passero One" => "Passero One"
		,"Passion One" => "Passion One"
		,"Pathway Gothic One" => "Pathway Gothic One"
		,"Patrick Hand" => "Patrick Hand"
		,"Patrick Hand SC" => "Patrick Hand SC"
		,"Patua One" => "Patua One"
		,"Paytone One" => "Paytone One"
		,"Peralta" => "Peralta"
		,"Permanent Marker" => "Permanent Marker"
		,"Petit Formal Script" => "Petit Formal Script"
		,"Petrona" => "Petrona"
		,"Philosopher" => "Philosopher"
		,"Piedra" => "Piedra"
		,"Pinyon Script" => "Pinyon Script"
		,"Pirata One" => "Pirata One"
		,"Plaster" => "Plaster"
		,"Play" => "Play"
		,"Playball" => "Playball"
		,"Playfair Display" => "Playfair Display"
		,"Playfair Display SC" => "Playfair Display SC"
		,"Podkova" => "Podkova"
		,"Poiret One" => "Poiret One"
		,"Poller One" => "Poller One"
		,"Poly" => "Poly"
		,"Pompiere" => "Pompiere"
		,"Pontano Sans" => "Pontano Sans"
		,"Port Lligat Sans" => "Port Lligat Sans"
		,"Port Lligat Slab" => "Port Lligat Slab"
		,"Prata" => "Prata"
		,"Preahvihear" => "Preahvihear"
		,"Press Start 2P" => "Press Start 2P"
		,"Princess Sofia" => "Princess Sofia"
		,"Prociono" => "Prociono"
		,"Prosto One" => "Prosto One"
		,"Puritan" => "Puritan"
		,"Purple Purse" => "Purple Purse"
		,"Quando" => "Quando"
		,"Quantico" => "Quantico"
		,"Quattrocento" => "Quattrocento"
		,"Quattrocento Sans" => "Quattrocento Sans"
		,"Questrial" => "Questrial"
		,"Quicksand" => "Quicksand"
		,"Quintessential" => "Quintessential"
		,"Qwigley" => "Qwigley"
		,"Racing Sans One" => "Racing Sans One"
		,"Radley" => "Radley"
		,"Raleway" => "Raleway"
		,"Raleway Dots" => "Raleway Dots"
		,"Rambla" => "Rambla"
		,"Rammetto One" => "Rammetto One"
		,"Ranchers" => "Ranchers"
		,"Rancho" => "Rancho"
		,"Rationale" => "Rationale"
		,"Redressed" => "Redressed"
		,"Reenie Beanie" => "Reenie Beanie"
		,"Revalia" => "Revalia"
		,"Ribeye" => "Ribeye"
		,"Ribeye Marrow" => "Ribeye Marrow"
		,"Righteous" => "Righteous"
		,"Risque" => "Risque"
		,"Roboto" => "Roboto"
		,"Roboto Condensed" => "Roboto Condensed"
		,"Roboto Slab" => "Roboto Slab"
		,"Rochester" => "Rochester"
		,"Rock Salt" => "Rock Salt"
		,"Rokkitt" => "Rokkitt"
		,"Romanesco" => "Romanesco"
		,"Ropa Sans" => "Ropa Sans"
		,"Rosario" => "Rosario"
		,"Rosarivo" => "Rosarivo"
		,"Rouge Script" => "Rouge Script"
		,"Ruda" => "Ruda"
		,"Rufina" => "Rufina"
		,"Ruge Boogie" => "Ruge Boogie"
		,"Ruluko" => "Ruluko"
		,"Rum Raisin" => "Rum Raisin"
		,"Ruslan Display" => "Ruslan Display"
		,"Russo One" => "Russo One"
		,"Ruthie" => "Ruthie"
		,"Rye" => "Rye"
		,"Sacramento" => "Sacramento"
		,"Sail" => "Sail"
		,"Salsa" => "Salsa"
		,"Sanchez" => "Sanchez"
		,"Sancreek" => "Sancreek"
		,"Sansita One" => "Sansita One"
		,"Sarina" => "Sarina"
		,"Satisfy" => "Satisfy"
		,"Scada" => "Scada"
		,"Schoolbell" => "Schoolbell"
		,"Seaweed Script" => "Seaweed Script"
		,"Sevillana" => "Sevillana"
		,"Seymour One" => "Seymour One"
		,"Shadows Into Light" => "Shadows Into Light"
		,"Shadows Into Light Two" => "Shadows Into Light Two"
		,"Shanti" => "Shanti"
		,"Share" => "Share"
		,"Share Tech" => "Share Tech"
		,"Share Tech Mono" => "Share Tech Mono"
		,"Shojumaru" => "Shojumaru"
		,"Short Stack" => "Short Stack"
		,"Siemreap" => "Siemreap"
		,"Sigmar One" => "Sigmar One"
		,"Signika" => "Signika"
		,"Signika Negative" => "Signika Negative"
		,"Simonetta" => "Simonetta"
		,"Sintony" => "Sintony"
		,"Sirin Stencil" => "Sirin Stencil"
		,"Six Caps" => "Six Caps"
		,"Skranji" => "Skranji"
		,"Slackey" => "Slackey"
		,"Smokum" => "Smokum"
		,"Smythe" => "Smythe"
		,"Sniglet" => "Sniglet"
		,"Snippet" => "Snippet"
		,"Snowburst One" => "Snowburst One"
		,"Sofadi One" => "Sofadi One"
		,"Sofia" => "Sofia"
		,"Sonsie One" => "Sonsie One"
		,"Sorts Mill Goudy" => "Sorts Mill Goudy"
		,"Source Code Pro" => "Source Code Pro"
		,"Source Sans Pro" => "Source Sans Pro"
		,"Special Elite" => "Special Elite"
		,"Spicy Rice" => "Spicy Rice"
		,"Spinnaker" => "Spinnaker"
		,"Spirax" => "Spirax"
		,"Squada One" => "Squada One"
		,"Stalemate" => "Stalemate"
		,"Stalinist One" => "Stalinist One"
		,"Stardos Stencil" => "Stardos Stencil"
		,"Stint Ultra Condensed" => "Stint Ultra Condensed"
		,"Stint Ultra Expanded" => "Stint Ultra Expanded"
		,"Stoke" => "Stoke"
		,"Strait" => "Strait"
		,"Sue Ellen Francisco" => "Sue Ellen Francisco"
		,"Sunshiney" => "Sunshiney"
		,"Supermercado One" => "Supermercado One"
		,"Suwannaphum" => "Suwannaphum"
		,"Swanky and Moo Moo" => "Swanky and Moo Moo"
		,"Syncopate" => "Syncopate"
		,"Tangerine" => "Tangerine"
		,"Taprom" => "Taprom"
		,"Tauri" => "Tauri"
		,"Telex" => "Telex"
		,"Tenor Sans" => "Tenor Sans"
		,"Text Me One" => "Text Me One"
		,"The Girl Next Door" => "The Girl Next Door"
		,"Tienne" => "Tienne"
		,"Tinos" => "Tinos"
		,"Titan One" => "Titan One"
		,"Titillium Web" => "Titillium Web"
		,"Trade Winds" => "Trade Winds"
		,"Trocchi" => "Trocchi"
		,"Trochut" => "Trochut"
		,"Trykker" => "Trykker"
		,"Tulpen One" => "Tulpen One"
		,"Ubuntu" => "Ubuntu"
		,"Ubuntu Condensed" => "Ubuntu Condensed"
		,"Ubuntu Mono" => "Ubuntu Mono"
		,"Ultra" => "Ultra"
		,"Uncial Antiqua" => "Uncial Antiqua"
		,"Underdog" => "Underdog"
		,"Unica One" => "Unica One"
		,"UnifrakturCook" => "UnifrakturCook"
		,"UnifrakturMaguntia" => "UnifrakturMaguntia"
		,"Unkempt" => "Unkempt"
		,"Unlock" => "Unlock"
		,"Unna" => "Unna"
		,"VT323" => "VT323"
		,"Vampiro One" => "Vampiro One"
		,"Varela" => "Varela"
		,"Varela Round" => "Varela Round"
		,"Vast Shadow" => "Vast Shadow"
		,"Vibur" => "Vibur"
		,"Vidaloka" => "Vidaloka"
		,"Viga" => "Viga"
		,"Voces" => "Voces"
		,"Volkhov" => "Volkhov"
		,"Vollkorn" => "Vollkorn"
		,"Voltaire" => "Voltaire"
		,"Waiting for the Sunrise" => "Waiting for the Sunrise"
		,"Wallpoet" => "Wallpoet"
		,"Walter Turncoat" => "Walter Turncoat"
		,"Warnes" => "Warnes"
		,"Wellfleet" => "Wellfleet"
		,"Wendy One" => "Wendy One"
		,"Wire One" => "Wire One"
		,"Yanone Kaffeesatz" => "Yanone Kaffeesatz"
		,"Yellowtail" => "Yellowtail"
		,"Yeseva One" => "Yeseva One"
		,"Yesteryear" => "Yesteryear"
		,"Zeyada" => "Zeyada"
	);
	
	global $default_custom_style_config,$wd_custom_style_config;
	$default_custom_style_config = array(
						'enable_custom_preview' 		=> 0
						,'enable_custom_font' 			=> 0
						,'enable_custom_color' 			=> 0
						,'page_layout' 					=> 'wide'
						,'font_sort' 					=>  "popularity"
						
						/******** Body font *******/
						,"body_font_name" 				=> "-1"
						,"body_font_style"				=> "normal"
						,"body_font_style_str" 			=> ""
						,"body_font_weight" 			=> "normal"

						
						/******** Heading font *******/
						,"heading_font_name" 			=> "-1"
						,"heading_font_style" 			=> "normal"
						,"heading_font_style_str" 		=> ""
						,"heading_font_weight" 			=> "normal"	
						
						/******** Menu font *******/
						,"menu_font_name" 				=> "-1"
						,"menu_font_style" 				=> "normal"
						,"menu_font_style_str" 			=> ""
						,"menu_font_weight" 			=> "normal"
						
						/******** Menu font *******/
						,"sub_menu_font_name" 				=> "-1"
						,"sub_menu_font_style" 				=> "normal"
						,"sub_menu_font_style_str" 			=> ""
						,"sub_menu_font_weight" 			=> "normal"

						,'primary_color' 					=> "#000"
						,'secondary_color' 					=> "#BE0404"

						,'header_top_background' => '#000' 
						,'header_top_text_color' => '#fff' 
						,'header_top_link_color' => '#999' 
						,'header_top_social_background_hover' => '#fff' 
						,'header_menu_text_color' => '#999' 
						,'header_menu_active_text_color' => '#000' 
						,'header_submenu_text_color' => '#666' 
						,'header_submenu_link_color' => '#000' 
						,'header_submenu_border_top_color' => '#000' 
						,'header_submenu_border_color' => '#d7d7d7' 
						,'header_submenu_hover_item_color' => '#000' 
						
						
						,'footer_first_area_background_color' => 'rgba(0,0,0,0.08)' 
						,'footer_first_area_text_color' => '#666' 
						,'footer_first_area_link_color' => '#000' 
						,'footer_first_area_link_color_hover' => '#BE0404' 		
						,'footer_first_area_heading_color' => '#000' 
						,'footer_first_area_border_color' => '#c1bfc0' 

						,'footer_second_area_background_color' => '#000' 
						,'footer_second_area_text_color' => '#666' 
						,'footer_second_area_link_color' => '#fff' 
						,'footer_second_area_link_color_hover' => '#BE0404' 		
						,'footer_second_area_heading_color' => '#fff' 
						,'footer_second_area_border_color' => '#c0c0bf' 

						,'footer_thrid_area_background_color' => '#000' 
						,'footer_thrid_area_text_color' => '#666' 
						,'footer_thrid_area_link_color' => '#666' 
						,'footer_thrid_area_link_color_hover' => '#fff' 		
						,'footer_thrid_area_border_color' => '#212121' 						
						
						,'sidebar_text_color' => '#666'
						,'sidebar_link_color' => '#000'
						,'sidebar_link_color_hover' => '#BE0404'
						,'sidebar_heading_color' => '#000'
						,'sidebar_border_color' => '#cfcfcf'
	

						,'primary_text_color' => '#666'
						,'primary_link_color' => '#000'
						,'primary_link_color_hover' => '#BE0404'
						,'primary_heading_color' => '#000'		
						,'primary_button_background_color' => '#000'
						,'primary_button_border_color' => '#000'
						,'primary_button_text_color' => '#fff'
						,'primary_button_background_color_hover' => '#BE0404'
						,'primary_button_border_color_hover' => '#BE0404'
						,'primary_button_text_color_hover' => '#fff'
						,'secondary_button_background_color' => '#fff'
						,'secondary_button_border_color' => '#000'		
						,'secondary_button_text_color' => '#000'
						,'secondary_button_background_color_hover' => '#fff'
						,'secondary_button_border_color_hover' => '#BE0404'
						,'secondary_button_text_color_hover' => '#BE0404'
						
						,'primary_border_color' => '#000'
						,'primary_border_color_hover' => '#BE0404'
						,'secondary_border_color' => '#d9d9d9'
						,'secondary_border_color_hover' => '#000'		
						,'primary_tab_background_color' => '#000'
						,'primary_tab_border_color' => '#000'
						,'primary_tab_text_color' => '#666'
						,'primary_tab_active_text_color' => '#fff'

						,'cart_icon_color' => '#fff' 
						,'cart_background_color' => '#000' 
						,'cart_background_color_hover' => '#BE0404' 
						,'feedback_background' => '#000' 
						,'feedback_background_hover' => '#BE0404' 
						,'totop_background' => '#000' 		
						,'totop_background_hover' => '#BE0404' 
						,'scollbar' => '#000' 
						,'rating_color' => '#000' 
						,'quickshop_text_color' => '#fff' 
						,'quickshop_background_color' => '#000' 		
						,'quickshop_background_color_hover' => '#BE0404'		
	);
	
	global $wd_custom_size;
	$_default_size = array(
							array(1200,450)
							,array(960,350)
							,array(190,122)
						);
	$wd_custom_size = get_option(THEME_SLUG.'custom_size','');
	if( strlen($wd_custom_size) > 0 ){
		$wd_custom_size = unserialize($wd_custom_size);
	}else{
		$wd_custom_size = $_default_size ;
	}


	function init_default_data( $smof_data ){
		$smof_data = wd_array_atts(	array(
				'wd_logo' 							=> ''
				,'wd_icon' 							=> get_stylesheet_directory_uri(). '/images/favicon.ico'
				,'wd_text_logo' 					=> "Sneaker"
				,'wd_enable_banner_top_main_content' 	=> 1
				,'wd_banner_top_main_content' 		=> '<div style="text-align:center"><span style="color:#c30005">"IT \'S TIME CRAZY SHOPPING TIME"</span> with over <span>1000 GIFTS</span> and <span>FREE SHIPPING</span></div>'
				,'wd_paypal_image'					=> ''
				,'wd_visa_image'					=> ''
				,'wd_master_card_image'				=> ''
				,'wd_verified_visa_image'			=> ''
				,'wd_trusted_visa_image'			=> ''
				,'wd_size1_width' 					=> 1200
				,'wd_size1_height' 					=> 450
				,'wd_size2_width' 					=> 960
				,'wd_size2_height' 					=> 300
				,'wd_size3_width' 					=> 480	
				,'wd_size3_height' 					=> 320
				,'wd_show_feedback_button' 			=> 1
				,'wd_feedback_button_image'			=> get_stylesheet_directory_uri(). '/images/feedback.png'
				,'wd_feedback_dialog_content' 		=> '[contact-form-7 id="4" title="Contact form 1"]'
				,'footer_text' 						=> '&copy; 2014 Sneaker Demo Store. Designed by <a href="http://wpdance.com/" title="WordPress Themes">WPDance.com</a>. WPDance is a member of <a href="http://www.emthemes.com/" title="Magento Themes">EMThemes</a>'	
				,'wd_show_body_end_widget_area'		=> 1
				,'wd_show_first_footer_widget_area' => 1
				,'wd_show_footer_menu' 				=> 1
				,'wd_show_end_footer_area' 			=> 1
				,'wd_preview_panel' 				=> 0
				,'wd_nicescroll' 					=> 0
				,'wd_sticky_menu' 					=> 1
				,'wd_effect_product'				=> 1
				,'wd_layout_styles' 				=> "wide"	
				,'wd_main_content_background'		=> "#ffffff"
				,'wd_body_end_background'			=> "#ffffff"
				,'wd_theme_color_primary' 			=> "#000000"
				,'wd_theme_color_secondary' 		=> "#c30005"
				,'wd_text_color' 					=> "#969696"
				,'wd_link_color' 					=> "#000000"
				,'wd_link_color_hover' 				=> "#c30005"
				,'wd_button_background' 			=> "#c30005"
				,'wd_button_background_hover' 		=> "#000000"
				,'wd_button_text' 					=> "#ffffff"
				,'wd_button_text_hover' 			=> "#ffffff"
				,'wd_heading_color' 				=> "#141414"
				,'wd_header_top_background' 		=> "#000000"
				,'wd_header_top_text_color' 		=> "#c8c8c8"	
				,'wd_header_top_text_hover' 		=> "#ffffff"
				,'wd_menu_background' 				=> "#dcdcdc"
				,'wd_menu_text_color' 				=> "#000000"
				,'wd_menu_text_color_hover' 		=> "#c30005"
				,'wd_sub_menu_background' 			=> "#ffffff"
				,'wd_sub_menu_border' 				=> "#cccccc"
				,'wd_sub_menu_text_color' 			=> "#969696"
				,'wd_sub_menu_text_color_hover' 	=> "#c30005"
				,'wd_phone_background' 				=> "#000000"
				,'wd_phone_text_color' 				=> "#ffffff"
				,'wd_phone_sub_text_color' 			=> "#aaaaaa"
				,'wd_testimonial_background' 		=> "#dcdcdc"
				,'wd_product_name_color' 			=> "#000000"
				,'wd_special_color' 				=> "#00387f"
				,'wd_border_color' 					=> "#dcdcdc"
				,'wd_border_color_hover' 			=> "#aaaaaa"
				,'wd_link_title_portfolio' 			=> "#969696"
				,'wd_link_title_portfolio_hover'	=> "#000000"
				,'wd_background_button_portfolio' 	=> "#000000"
				,'wd_background_button_portfolio_hover' 	=> "#c30005"
				,'wd_border_portfolio_hover' 		=> "#000000"
				,'wd_button_cart_background' 		=> "#c8c8c8"
				,'wd_button_cart_background_hover' 	=> "#c30005"
				,'wd_button_cart_text' 				=> "#ffffff"
				,'wd_button_cart_text_hover' 		=> "#ffffff"
				,'wd_text_price_color' 				=> "#646464"
				,'wd_rating_color' 					=> "#c30005"
				,'wd_text_price_sale_color' 		=> "#c30005"
				,'wd_footer_background' 			=> "#eeeeee"
				,'wd_footer_subscriptions_background' 		=> "#eeeeee"
				,'wd_footer_end_background' 		=> "#000000"
				,'wd_footer_end_menu_text' 			=> "#ffffff"
				,'wd_footer_end_menu_text_hover' 	=> "#969696"
				,'wd_footer_end_text' 				=> "#646464"
				,'wd_feature_sale'					=> "#003782"
				,'wd_feature_sale_text_color'		=> "#ffffff"
				,'wd_feature_new'					=> "#f5d200"
				,'wd_feature_new_text_color'		=> "#ffffff"
				,'wd_feature_hot'					=> "#c8000a"
				,'wd_feature_hot_text_color'		=> "#ffffff"
				,'wd_button_slider_background'		=> '#1e1e1e'
				,'wd_button_slider_icon'			=> '#ffffff'
				,'wd_social_border'					=> '#969696'
				,'wd_social_text'					=> '#969696'
				,'wd_sidebar_title_background'		=> '#000000'
				,'wd_sidebar_title_color'			=> '#ffffff'
				,'wd_body_font_googlefont_enable' 	=> 1
				,'wd_body_font_family' 				=> "Arial"
				,'wd_body_font_googlefont' 			=> "Roboto"
				,'wd_body_second_font_googlefont_enable' 	=> 1
				,'wd_body_second_font_family' 				=> "Open Sans"
				,'wd_body_second_font_googlefont' 			=> "Roboto"
				,'wd_heading_font_googlefont_enable' 		=> 1
				,'wd_heading_fontfamily' 			=> "Open Sans"
				,'wd_heading_font_googlefont' 		=> "Share"
				,'wd_menu_font_googlefont_enable' 	=> 1
				,'wd_menu_fontfamily' 				=> "Open Sans"
				,'wd_menu_font_googlefont' 			=> "Share"
				,'wd_sub_menu_font_googlefont_enable' 	=> 1
				,'wd_sub_menu_fontfamily' 			=> "Open Sans"
				,'wd_sub_menu_font_googlefont' 		=> "Roboto"
				,'wd_price_font_googlefont_enable' 	=> 1
				,'wd_price_fontfamily' 				=> 'Open Sans'
				,'wd_price_font_googlefont' 		=> "Roboto"
				,'wd_menu_thumb_width' 				=> 16
				,'wd_menu_thumb_height' 			=> 16
				,'wd_menu_num_widget' 				=> 5
				,'wd_qs_button_label' 				=> __("Quickshop","wpdance")
				,'wd_qs_button_imgage' 				=> ""
				,'wd_quickshop_background' 			=> "#000000"
				,'wd_quickshop_text_color' 			=> "#ffffff"
				,'wd_quickshop_background_hover' 	=> "#c30005"
				,'wd_quickshop_text_color_hover' 	=> "#ffffff"
				,'wd_qs_product_title' 				=> 1
				,'wd_qs_product_label' 				=> 1
				,'wd_qs_product_availability' 		=> 1
				,'wd_qs_product_sku' 				=> 1
				,'wd_qs_product_rating' 			=> 1
				,'wd_qs_product_short_description' 	=> 1
				,'wd_qs_product_add_to_cart' 		=> 1
				,'wd_enable_advertisement' 			=> 0
				,'wd_advertisement_code' 			=> '<div class="wd-shipping"><a style="color:#00387f" class="shipping" href="#">Free shipping for over $200.00 orders</a><a style="color:#c30005" class="gifts" href="#">Gifts for over $100 orders </a></div>
														<ul class="menu-advertisment">
														<li><a href="#">$5 DVDs</a></li>
														<li><a href="#">$10 Blu-ray Discs</a></li>
														<li><a href="#">Preorders</a></li>
														<li><a class="wd-important" href="#">Deals</a></li>
														</ul>'
				,'wd_top_blog_code' 				=> ""
				,'wd_bottom_blog_code' 				=> ""
				,'wd_before_body_end_code' 			=> ""
				,'wd_google_analytic_code' 			=> ""
				
				,'wd_shop_slider_slide_speed_pc' 	=> "800"
				,'wd_shop_slider_slide_speed_mobile'=> "200"
				,'wd_shop_slider_scroll_per_page' 	=> 0
				,'wd_shop_slider_rewind_nav' 		=> 1
				,'wd_shop_slider_rewind_speed' 		=> "800"
				,'wd_shop_slider_auto_play' 		=> 0
				,'wd_shop_slider_stop_on_hover' 	=> 0
				,'wd_shop_slider_mouse_drag' 		=> 0
				,'wd_shop_slider_touch_drag' 		=> 1
				
				,'wd_prod_cat_column' 				=> 4
				,'wd_prod_cat_per_page' 			=> 12
				,'wd_prod_cat_layout' 				=> "0-1-1"
				,'wd_prod_cat_left_sidebar' 		=> "category-widget-area-left"
				,'wd_prod_cat_right_sidebar' 		=> "category-widget-area-right"
				,'wd_prod_cat_rating' 				=> 1
				,'wd_prod_cat_categories' 			=> 0
				,'wd_prod_cat_title' 				=> 1
				,'wd_prod_cat_sku' 					=> 0
				,'wd_prod_cat_disc_grid' 			=> 0
				,'wd_prod_cat_disc_list' 			=> 1
				,'wd_prod_cat_price' 				=> 1
				,'wd_prod_cat_add_to_cart' 			=> 1
				,'wd_prod_left_sidebar' 			=> "product-widget-area-left"
				,'wd_prod_right_sidebar' 			=> "product-widget-area-right"
				,'wd_prod_image' 					=> 1	
				,'wd_prod_cloudzoom' 				=> 1
				,'wd_prod_label' 					=> 1
				,'wd_prod_title' 					=> 1
				,'wd_prod_email_friend' 			=> 1
				,'wd_prod_sku' 						=> 1
				,'wd_prod_rating' 					=> 1
				,'wd_prod_review' 					=> 1
				,'wd_prod_availability' 			=> 1
				,'wd_prod_cart' 					=> 1
				,'wd_prod_price' 					=> 1
				,'wd_prod_shortdesc' 				=> 1
				,'wd_prod_meta' 					=> 1
				,'wd_prod_related' 					=> 1
				,'wd_prod_related_title' 			=> __('RELATED ITEMS','wpdance')
				,'wd_prod_upsell' 					=> 1
				,'wd_prod_upsell_title' 			=> __('YOU MAY ALSO LIKE','wpdance')
				,'wd_prod_share' 					=> 1
				,'wd_prod_share_title' 				=> __('Share thist','wpdance')
				,'wd_prod_ship_return' 				=> 1	
				,'wd_prod_ship_return_title' 		=> ""	
				,'wd_prod_ship_return_content' 		=> '<div class="wd-bottom-banner-left one_half">
														<a class="wd-effect-normal"><img title="banner" alt="banner" src="http://demo2.wpdance.com/imgs/wp_Sneaker/banner-bottom-product.jpg" />
														</a></div><div class="wd-bottom-banner-right one_half last">
														<a class="wd-effect-normal"><img title="banner" alt="banner" src="http://demo2.wpdance.com/imgs/wp_Sneaker/banner-bottom-product.jpg" /></a></div>'	
				,'wd_prod_tabs' 					=> 1	
				,'wd_prod_customtab' 				=> 1
				,'wd_prod_customtab_title' 			=> __('Custom Tab','wpdance')
				,'wd_prod_customtab_content' 		=> "custom contents go here"
				,'wd_prod_layout' 					=> "0-1-1"
				,'wd_blog_categories' 				=> 0
				,'wd_blog_author' 					=> 1
				,'wd_blog_time' 					=> 1
				,'wd_blog_comment_number' 			=> 1
				,'wd_blog_excerpt' 					=> 1			
				,'wd_blog_thumbnail' 				=> 1
				,'wd_blog_readmore' 				=> 1
				,'wd_blog_details_categories' 		=> 1
				,'wd_blog_details_author' 			=> 1
				,'wd_blog_details_time' 			=> 1
				,'wd_blog_details_tags' 			=> 1
				,'wd_blog_details_thumbnail' 		=> 1
				,'wd_blog_details_comment' 			=> 1
				,'wd_blog_details_socialsharing' 	=> 1
				,'wd_blog_details_authorbox' 		=> 1
				,'wd_blog_details_related' 			=> 1
				,'wd_blog_details_relatedlabel' 	=> __("Related Posts","wpdance")
				,'wd_blog_details_commentlist' 		=> 1
				,'wd_blog_details_commentlabel' 	=> __("Comment","wpdance")		
			),
			$smof_data
		);	
		return $smof_data;
	}
	
	if( !is_admin() ){
		add_action('init', 'my_wd_modify_default',10);
	}
	function my_wd_modify_default($smof_data){
		global $smof_data;
		$smof_data = init_default_data( $smof_data );
		return $smof_data;
	}
	
	function datas_config($smof_data = array()){
		//global $smof_data;
		$smof_data = $smof_data['data'];
		if($smof_data && isset($smof_data['wd_menu_num_widget'],$smof_data['wd_menu_thumb_width'],$smof_data['wd_menu_thumb_height'])){
			$wd_mega_menu_config_arr = array(
				'area_number' => $smof_data['wd_menu_num_widget']
				,'thumbnail_width' => $smof_data['wd_menu_thumb_width']
				,'thumbnail_height' => $smof_data['wd_menu_thumb_height']
			);
			update_option(THEME_SLUG.'wd_mega_menu_config',serialize($wd_mega_menu_config_arr));
		}
	}
	add_action('of_save_options_after','datas_config',20);
?>